rm -rf ../jdk-18_linux-x64_bin.tar.gz
rm -rf ../mongodb-linux-x86_64-ubuntu2004-6.0.0.tgz
rm -rf build
rm -rf gradle
rm -rf install.sh
rm -rf README_es-ES.md
rm -rf README_zh-CN.md
rm -rf start_config.cmd
rm -rf build.gradle
rm -rf gradlew
rm -rf README_fr-FR.md
rm -rf README_zh-TW.md
rm -rf CODE_OF_CONDUCT.md
rm -rf gradlew.bat
rm -rf README_HE.md
rm -rf settings.gradle
rm -rf CONTRIBUTING.md
rm -rf LICENSE       
rm -rf README.md
rm -rf src
rm -rf format_whitespace.py
rm -rf Grasscutter_Resources
rm -rf manage_languages.py
rm -rf __pycache__
rm -rf README_ru-RU.md
rm -rf start.cmd
rm -rf delete.sh